name: CI/ Fullstack test and Sonar scan Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
  # --- JOB FRONTEND ---
  # On le garde à part car il n'a pas besoin de Java
  # --- JOB FRONTEND ---
  # On le garde à part car il n'a pas besoin de Java

jobs:
  # --- JOB FRONTEND ---
  # On le garde à part car il n'a pas besoin de Java
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'

      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./front
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage/

  # --- JOB BACKEND + SONAR ---
  # On fusionne pour que Sonar trouve les fichiers binaires (.class)
  build-and-analyze:
    runs-on: ubuntu-latest
    needs: frontend-tests # Optionnel : n'analyse que si le front est OK
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour Sonar

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test Backend
        working-directory: ./back
        # On fait un install pour générer le dossier target/classes
        run: mvn clean test

      - name: Generate JaCoCo Coverage Report
        working-directory: ./back
        run: mvn jacoco:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco/

      - name: SonarQube Scan
        uses: sonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            projectBaseDir: .
